services:
  - type: web
    name: skyfreelanc-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python justjobs.py
    envVars:
      - key: TOKEN
        fromSecret: TOKEN
      - key: CHANNEL
        fromSecret: CHANNEL
