
services:
  - type: web
    name: skyfreelanc-bot
    runtime: python3.11
    plan: free
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TOKEN
        fromSecret: TOKEN
      - key: CHANNEL
        fromSecret: CHANNEL
